// Generates supabase/seed.sql from data/exams/*.json.
// Run from the repo root: dart data/tool/build_seed.dart
import 'dart:convert';
import 'dart:io';

const examNames = {
  'up_police_constable': ('यूपी पुलिस कांस्टेबल', 'UP Police Constable'),
  'ssc_gd': ('SSC GD कांस्टेबल', 'SSC GD Constable'),
  'delhi_police_constable': (
    'दिल्ली पुलिस कांस्टेबल',
    'Delhi Police Constable',
  ),
  'agniveer_army_gd': ('अग्निवीर थल सेना (GD)', 'Agniveer Army (GD)'),
};

String q(Object? v) {
  if (v == null) return 'null';
  if (v is num || v is bool) return '$v';
  return "'${v.toString().replaceAll("'", "''")}'";
}

void main() {
  final files =
      Directory('data/exams')
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  final out = StringBuffer()
    ..writeln(
      '-- Generated by data/tool/build_seed.dart from data/exams/*.json. Do not edit by hand.',
    )
    ..writeln('begin;');

  for (final file in files) {
    final exam = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final id = exam['exam_id'] as String;
    final names = examNames[id];
    if (names == null) {
      stderr.writeln('No display names for $id in build_seed.dart');
      exit(1);
    }
    final sources = exam['sources'] as Map<String, dynamic>?;
    final notificationUrl = sources == null
        ? null
        : (sources.values.first as Map<String, dynamic>)['url'];

    out
      ..writeln()
      ..writeln(
        'insert into public.exams (id, name_hi, name_en, notification_url, data_version)',
      )
      ..writeln(
        'values (${q(id)}, ${q(names.$1)}, ${q(names.$2)}, ${q(notificationUrl)}, ${q(exam['data_version'])})',
      )
      ..writeln(
        'on conflict (id) do update set name_hi = excluded.name_hi, name_en = excluded.name_en,',
      )
      ..writeln(
        '  notification_url = excluded.notification_url, data_version = excluded.data_version;',
      )
      ..writeln('delete from public.standards where exam_id = ${q(id)};')
      ..writeln(
        'insert into public.standards (exam_id, gender, category, event, kind, value, source_url, verified, age_min, age_max, reported_value) values',
      );

    final rows = (exam['standards'] as List).cast<Map<String, dynamic>>().map((
      s,
    ) {
      if (s['verified'] == true &&
          (s['value'] == null || s['source_url'] == null)) {
        stderr.writeln('$id: verified row without value or source_url: $s');
        exit(1);
      }
      return '  (${q(id)}, ${q(s['gender'])}, ${q(s['category'])}, ${q(s['event'])}, '
          '${q(s['kind'])}, ${q(s['value'])}, ${q(s['source_url'])}, ${q(s['verified'] == true)}, '
          '${q(s['age_min'])}, ${q(s['age_max'])}, ${q(s['reported_value'])})';
    });
    out.writeln('${rows.join(',\n')};');
  }

  out.writeln('\ncommit;');
  File('supabase/seed.sql').writeAsStringSync(out.toString());
  stdout.writeln('Wrote supabase/seed.sql from ${files.length} exam files.');
}
